project_name: celguard

builds:
  - id: celguard
    main: .
    env:
      - CGO_ENABLED=0
    goos: [linux]
    goarch: [amd64]
    binary: celguard_linux_x86_64
    flags: [-trimpath]
    ldflags:
      - -s
      - -w

checksum:
  name_template: 'checksums.txt'
