name: PRLint
description: Pull Request Linter with CEL
author: konojunya
inputs:
  config:
    description: 'Path to the config file'
    required: true
    default: '.github/prlint.yaml'
  version:
    description: 'Version to use'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: resolve version
      id: v
      shell: bash
      run: |
        set -euo pipefail
        if [[ -n "${{ inputs.version }}" ]]; then
          echo "tag=${{ inputs.version }}" >> $GITHUB_OUTPUT
        else
          tag=$(gh release view --json tagName -q .tagName || true)
          if [[ -z "$tag" ]]; then
            tag=$(curl -sSfL -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/konojunya/prlint/releases/latest | jq -r '.tag_name')
          fi
          echo "tag=${tag}" >> $GITHUB_OUTPUT
        fi
    - name: download prlint
      shell: bash
      env:
        TAG: ${{ steps.v.outputs.tag }}
      run: |
        set -euo pipefail
        base="https://github.com/konojunya/prlint/releases/download/${TAG}"
        curl -LsSf "${base}/prlint_${TAG#v}_linux_amd64.tar.gz" -o prlint.tar.gz
        curl -LsSf "${base}/checksums.txt" -o checksums.txt

        # checksum verification
        grep prlint_${TAG#v}_linux_amd64.tar.gz checksums.txt | sha256sum --check --status || {
          echo "::error::Checksum mismatch"
          exit 2
        }
        tar -xzf prlint.tar.gz
        chmod +x prlint_linux_x86_64
        mv prlint_linux_x86_64 prlint
    - name: run prlint
      shell: bash
      run: ./prlint ${{ inputs.config }}

branding:
  icon: 'git-pull-request'
  color: 'white'
